### ISSUE TITLE
Unknown log opt 'syslog-tag' for syslog log driver

### ISSUE THREAD

**Issue by ismarslomic** [Accenture/adop-docker-compose#115]
### My environment:
- OSX 10.11.6
- Docker version 1.12.0-rc4, build e4a0dbc, experimental

### Docker info:
```
Ismars-iMac:~ ismarslomic$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 61
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 47
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.788 GiB
Name: moby
ID: 6KZS:ZCKP:VICU:BVCX:UBPK:GYBT:5UPI:G5QY:4LCZ:4RV6:EMJB:R5ON
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 28
 System Time: 2016-07-23T12:23:09.78445108Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

### Steps to reproduce error:
- git clone https://github.com/Accenture/adop-docker-compose
- ./quickstart.sh -t local -m adop-machine -u ismar -p slomic

### Error displayed in console (after pulling Docker images is done):
```
ERROR: for sensu-rabbitmq  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for sensu-client  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for nexus  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for gerrit-mysql  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for gerrit  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for jenkins-slave  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for sensu-api  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for sonar  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for selenium-hub  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for sensu-redis  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for selenium-node-chrome  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for proxy  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for ldap  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for selenium-node-firefox  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for sensu-uchiwa  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for jenkins  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for sonar-mysql  unknown log opt 'syslog-tag' for syslog log driver

ERROR: for sensu-server  unknown log opt 'syslog-tag' for syslog log driver
ERROR: Encountered errors while bringing up the project.
```

**Comment by ismarslomic** [comment]
Renaming log-opt option from `syslog-tag` to `tag` in `/etc/logging/syslog/default.yml` resolves this issue. I guess this is because Im running later version of Docker then this project? If so, README shall state which Docker version shall be installed as prerequisite!

**Comment by mihail-dev** [comment]
@ismarslomic you are right about replace the syslog-tag with tag as of docker version 1.12 syslog-tag has been deprecated - https://docs.docker.com/engine/deprecated/#/driver-specific-log-tags. 

Tag seems to be introduced in v1.12 so maybe it will not work for older versions of docker - https://docs.docker.com/engine/admin/logging/log_tags/?

**Comment by ismarslomic** [comment]
@mihail-dev: Im not sure if there are any solutions to make sure logs tags can be backward compatible. However, my point is that documentation shall state which Docker version must be installed and that is supported by the platform. Otherwise you will run in similar issues in upcoming releases of Docker.

**Comment by mihail-dev** [comment]
I agree with this, maybe you can submit a PR? 

Another way we can solve this is to create a second file like this one with the tag option instead of syslog-tag - https://github.com/Accenture/adop-docker-compose/blob/master/etc/logging/syslog/default.yml. Then depending on the docker version call the right file from here - https://github.com/Accenture/adop-docker-compose/blob/master/cmd/compose#L309.

**Comment by nickdgriffin** [comment]
In an ideal world Docker would stop introducing changes that weren't backwards compatible!

**Comment by ismarslomic** [comment]
@nickdgriffin good point, however, you should expect backward and non-backward compatible changes from Docker team as Docker is heavily under development in these days. This has of course challenges, but hopefully they are simplifying then complicating new ways of solving things. :)

**Comment by nickdgriffin** [comment]
@ismarslomic I always expect non-backward compatible changes, seeing as whenever Docker do anything major they always break something from a previous version. For example Compose v2 completely broke having multiple compose files with custom networks and logging drivers for v1, and didn't implement them fully in v2 (initially) so an upgrade wasn't immediately possible. It's tricky when they do stuff like this particular issue because if we update the etc/logging/syslog/default.yml it'll break it for everyone who isn't on 1.12 yet.

1.12 is probably the next version we'll end up sticking to though I expect because of the introduction of Swarm mode.
