### ISSUE TITLE
quickstart issue on linux

### ISSUE THREAD

**Issue by lucentj** [Accenture/adop-docker-compose#117]
The quick start continually fails on aws using Amazon Linux AMI 2016.03.3 (HVM) with the error

ERROR: .IOError: [Errno 2] No such file or directory: u'././compose/elk.yml'

this is the parameter passed to the docker-compose command. I've confirmed that compose/elk.yml exists. I've also started with a fresh image and a fresh clone of the code and quick start continually fails at this step.

**Comment by nickdgriffin** [comment]
That's interesting.

So the path to that file comes from:
`
ELKFILEOPTS="-f ${CLI_DIR}/compose/elk.yml"
`

And CLI_DIR comes from:
`
export CLI_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
`

So can you run the above and see what the output is please? 

I'd guess what's happening is that it's failing to determine the value for CLI_DIR correctly which is what is causing the problem, in which case it'd be useful to know the version of bash and sed you are using please.

**Comment by lucentj** [comment]
GNU sed version 4.2.1
GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)

Running the commands execute with no output and return to a prompt.

Running quickstart results in the same error

ERROR: .IOError: [Errno 2] No such file or directory: u'././compose/elk.yml'

**Comment by nickdgriffin** [comment]
Yes sorry should have been a bit clearer, if you run those exact commands you'll need to run this to see each as they are just setting a variable and environment variable respectively:
`echo $ELKFILEOPTS`
`echo $CLI_DIR`

**Comment by lucentj** [comment]
Yep I follow ... the environment variables are not set outside of running quickstart so they return nothing. I edited the compose file to echo the variables as quickstart was running and re-ran quickstart.

$ELKFILEOPTS returns:  -f ./compose/elk.yml

$CLI_DIR returns: .

**Comment by nickdgriffin** [comment]
Yeah, that's why I suggested just copying the commands I pasted in and running them in your shell before echoing them out.

I think I'm expecting them to return the absolute path but I'll confirm when I'm on a machine I can run it from.

**Comment by mihail-dev** [comment]
I've just tried this commands on RHEL 7 and these are the results:

```
[root@BLDSWMALLAP01 adop-docker-compose]#  ELKFILEOPTS="-f ${CLI_DIR}/compose/elk.yml"
[root@BLDSWMALLAP01 adop-docker-compose]#  export CLI_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
[root@BLDSWMALLAP01 adop-docker-compose]# echo $ELKFILEOPTS
-f ./compose/elk.yml
[root@BLDSWMALLAP01 adop-docker-compose]# echo $CLI_DIR
.
[root@BLDSWMALLAP01 adop-docker-compose]# cat /etc/*release*
LSB_VERSION=core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
cat: /etc/lsb-release.d: Is a directory
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
Red Hat Enterprise Linux Server release 7.2 (Maipo)
Red Hat Enterprise Linux Server release 7.2 (Maipo)
cpe:/o:redhat:enterprise_linux:7.2:ga:server
[root@BLDSWMALLAP01 adop-docker-compose]#
```

**Comment by nickdgriffin** [comment]
Well the paths are certainly what I'd expect with how we are working out the value of CLI_DIR, and I've not had any issue with this on CentOS Linux release 7.2.1511 with Docker Compose 1.8.0 and I've got the same version of bash and sed 4.2.2.

What version of Docker Compose are you using @lucentj please?

**Comment by lucentj** [comment]
docker-compose version 1.7.1, build 0a9ab35
