### ISSUE TITLE
docker-machine unable to find a subnet in  the zone if VPC is not in the AZ "a"

### ISSUE THREAD

**Issue by whren** [Accenture/adop-docker-compose#12]
Context
======

Follow the QuickStart instructions.
In my case, on the step 1, I created VPC in eu-west-1 region.
On step 3 run startup.sh without AWS credentials and default region stored locally in ~/.aws.
I used the following command :

./startup.sh -m adop1 -c <newly_vpcid> -r eu-west-1 -a AWS_ACCESS_KEY -s AWS_SECRET_ACCESS_KEY -v local -n adopnetwork

Expected
=======

docker-machine EC2 instance creation is OK

Actual
=====

docker-machine exited with the follwing error :

"Error creating machine: Error with pre-create check: unable to find a subnet in the zone: eu-west-1a"

Analysis
=======

In fact docker-machine create for amazon EC2 will always use the AZ "a" by default.

But on step "1.Create a VPC using the VPC wizard in the AWS console by selecting the first option with 1 public subnet" I did not fix the AZ to "a" and let the predefined "Availability Zone" field to "No preference".

So either you must fix "Availibility Zone" to "a" in the VPC creation wizard screen on step 1 or startup.sh needs to be fixed in order to introduce a new argument for docker-machine "--amazonec2-zone".

**Comment by nickdgriffin** [comment]
I think perhaps a better method would be to pass in the exact subnet where the machine should be created, but the sentiment is the same. Open to a PR for either.

**Comment by robwells57** [comment]
Forking repo. to add new command line option (-z) to specify subnet availability zone.

**Comment by nickdgriffin** [comment]
I believe this issue should now be resolved with the merging of the above PR.
