### ISSUE TITLE
Broken TravisCI builds with no reason

### ISSUE THREAD

**Issue by anton-kasperovich** [Accenture/adop-docker-compose#121]
From time to time we have broken TravisCI builds, even if functionality wasn't changed at all, like changing README files, some of examples:

- https://travis-ci.org/Accenture/adop-docker-compose/builds/147875007
- https://travis-ci.org/Accenture/adop-docker-compose/builds/147816624

If we would re-trigger these builds - they would be "green" and it's a bit confusing, why they fail from the beginning, i mean when build triggered automatically. Need to investigate.

**Comment by nickdgriffin** [comment]
Yeah, this is bugging me now so I'll see if I can take a look at why this is happening this week.
