### ISSUE TITLE
Enhancement: Platform Extension for CloudFormation to be orchestrated by Ansible

### ISSUE THREAD

**Issue by bzon** [Accenture/adop-docker-compose#133]
# Enhancement Summary

Instead of using AWS cli in the Platform Extension job's execute shell to run Cloudformation templates, we can utilize Ansible to orchestrate it and have a flexible way of launching user's templates without locking them with predefined 'CF parameters'. For now let's just focus on CloudFormation.  
# [Update]

Attached the sample screenshot from my Jenkins instance.

I just tested the whole suggestion working using our:
- [forked platform management](https://github.com/AccenturePDC/adop-b-framework-gitlab-platform-management/blob/feature-platform-extension/bootstrap/Platform_Management/Load_Platform_Extension.groovy)
- [forked chef adop extension](https://github.com/AccenturePDC/adop-platform-extension-chef/tree/master)
- [adop-docker-compose](https://github.com/AccenturePDC/adop-docker-compose) - A project that has a custom jenkins-slave container with ansible installed.
- [Jenkins-slave](https://github.com/bzon/adop-jenkins-slave/blob/ansible-feature/Dockerfile)
# Terminologies
- Playbook - the Ansible file or script. It's like the cookbook of Chef.
- Ansible CF module - [cloudformation_module](http://docs.ansible.com/ansible/cloudformation_module.html)
# Requirements to accomplish this:
- **Update the jenkins-slave**  - `yum install ansible python-boto` in the jenkins-slave.
- **Update the platform extension specification project** - Have a standardized name for the playbook like `cf-runner.yml`. Users will place the `cf-runner.yml` in the aws directory.

``` bash
service
|__aws
   |__ service.template
   |__ cf-runner.yml
```
- **Users customized their own cf-runner.yml** - so they can add their own Cloudformation parameters if they have to.  The example below runs the adop chef server extension's `service.template` using the ansible cloudformation module.

``` bash
- hosts: localhost
  connection: local
  tasks:
    - name: Launch cloudformation for Chef extension
      cloudformation:
        stack_name: "ansible-cloudformation"
        state: "present"
        region: "{{ lookup('env','AWS_REGION') }}"
        disable_rollback: true
        template: "service.template"
        # User defined parameters
        template_parameters:
          KeyName: "{{ lookup('env','AWS_KEYPAIR') }}"
          InstanceType: "t2.large"
          EnvironmentName: "ChefServer"
          EnvironmentSubnet: "{{ lookup('env','AWS_SUBNET_ID') }}"
          VPCId: "{{ lookup('env','AWS_VPC_ID') }}"
          InboundCIDR: "0.0.0.0/0"
        tags:
          Stack: "chef-stack"

      # Register the cloudformation output facts into a variable
      register: cf_out

    # Print the output to stdout
    - debug: var=cf_out

    - name: Copy all the output facts into a file
      copy: content={{ cf_out }} dest=./cf_out.json

    # Get the important data and create a file for it.
    # In this example, we want to save the ip address of the provisioned IP so we can parse it to a variable
    # for modifying the configuration file that will be copied over the ADOP nginx proxy container.
    - name: Copy the ip address attribute of the output facts into a file
      copy: content={{ cf_out["stack_outputs"]["EC2InstancePrivateIp"] }} dest=./instance_ip.txt
```
- Jenkins `execute shell` now will have something like this..

``` bash
# Provision any EC2 instances in the AWS folder
if [ -d ${WORKSPACE}/service/aws ]; then

    if [ -f ${WORKSPACE}/service/aws/service.template ] && [ -f ${WORKSPACE}/service/aws/cf-runner.yml ]; then

        echo "#######################################"
        echo "Adding EC2 platform extension on AWS..."

        cd service/aws/
        ansible-playbook cf-runner.yml
        if [[ $? -gt 0 ]]; then exit 1; fi
        cd -

        if [ -f ${WORKSPACE}/service/aws/ec2-extension.conf ]; then

            echo "#######################################"
            echo "Adding EC2 instance to NGINX config using xip.io..."

            export SERVICE_NAME="EC2-Service-Extension-${BUILD_NUMBER}"
            cp ${WORKSPACE}/service/aws/ec2-extension.conf ec2-extension.conf
            NODE_IP=$(cat ${WORKSPACE}/service/aws/instance_ip.txt)

            ## Add nginx configuration
            sed -i "s/###EC2_SERVICE_NAME###/${SERVICE_NAME}/" ec2-extension.conf
            sed -i "s/###EC2_HOST_IP###/${NODE_IP}/" ec2-extension.conf
            docker cp ec2-extension.conf proxy:/etc/nginx/sites-enabled/${SERVICE_NAME}.conf

            ## Reload nginx
            docker exec proxy /usr/sbin/nginx -s reload

            ## Don't stop jenkins to exit with error if nginx reload has failed.
            if [[ $? -gt 0 ]]; then
              echo "An error has been encountered while reloading nginx. There might be some upstreams that are not reachable."
              echo "Please run 'docker exec proxy /usr/sbin/nginx -s reload' to debug nginx."      
            fi

            echo "You can check that your EC2 instance has been succesfully proxied by accessing the following URL: ${SERVICE_NAME}.${PUBLIC_IP}.xip.io"
        else
            echo "INFO: /service/aws/ec2-extension.conf not found"
        fi

    else
        echo "INFO: /service/aws/service.template or /service/aws/cf-runner.yml not found."
    fi
fi
```
# Console Output

![adop-ext](https://cloud.githubusercontent.com/assets/19391568/17614826/129e8e54-609c-11e6-8131-f0281f1bb828.JPG)

**Comment by nickdgriffin** [comment]
Interesting stuff!

Could this be a way to launch new services via Ansible instead of specifically just being for AWS? i.e. it'd fall under service/ansible in the platform extension (and therefore be an addition to the spec).

I think I'd want this method to exist alongside the existing one instead of replacing it, just for compatibility, too.

**Comment by bzon** [comment]
@nickdgriffin the new way to launch new services, hopefully yes, there is a lot of ansible module that we can use to faciliate all of the extensions. E.g, for docker, the [container module](https://docs.ansible.com/ansible/docker_container_module.html) or [line in file](http://docs.ansible.com/ansible/lineinfile_module.html) to modify nginx configurations..

For making it compatible with the old style, we can create a wrapper script for all of those old aws cli commands/scripts to make  the `execute shell` as neat as possible.

**Comment by nickdgriffin** [comment]
I think in that case I could see this as "service/ansible" then instead of changing the existing "service/aws". I like the idea of having different ways to launch the same thing if it gives people the option of choosing their orchestration/deployment tool depending on what they are familiar with and what their use case is.

**Comment by bzon** [comment]
@nickdgriffin I agree with the "service/ansible" idea! :) 

FYI - @paoloxide @arcyteodoroacn

**Comment by anton-kasperovich** [comment]
@nickdgriffin agree, as tomorrow someone could try to change on Chef or Puppet or whatever tool :)
@bzon Would you have a time to implement it as "service/ansible"? Feel free to ask for any assistance on this, happy to help.

**Comment by bzon** [comment]
@anton-kasperovich I would be happy to. 

Let's plan this @paoloxide @arcyteodoroacn

**Comment by bzon** [comment]
I'm closing this issue at least for the meantime because I won't be able to look it because of a long term project priority commitments.
