### ISSUE TITLE
after upgrading slave machine, jobs fail as Docker version is not in sync between slave container and the others

### ISSUE THREAD

**Issue by deors** [Accenture/adop-docker-compose#14]
I think we should downgrade the slave version to 0.1.0, until all other images are also upgraded to Docker 1.10, as currently there are some issues because of the version mismatch when a docker command is executed inside the slave (i.e. creating environment, deploying a build to Tomcat node).

**Comment by nickdgriffin** [comment]
What counts as "all other images"? The reason the slave was upgraded to have Docker 1.10 was because Docker Machine (using the AMI we specify) was creating Docker 1.10 Engines and the Slave's 1.9.x client was refusing to work when creating and deploying an environment.

**Comment by deors** [comment]
That's a good point. AWS works fine actually, but not locally with Docker
Toolbox 1.9.0. I guess that what we should do to keep it working in
boot2docker is to update it to 1.10.0 and update docs to point to that
version. Tomorrow afternoon I may have some time and will upgrade to 1.10.0
in my PC and spawn a new VM with boot2docker. I'll keep you posted.

**Comment by nickdgriffin** [comment]
Cool, yes I think we could be a bit clearer in the readme on what version we expect to use.

**Comment by deors** [comment]
Already tried with Docker Toolbox 1.10.2 and the corresponding version of boot2docker. Everything worked fine in local VM this time. Only a minor caveat, the shell type in docker-machine env command was not detected as bash (using Git-bash on Windows machine), although with 1.9.0 it was. I have added the "--shell bash" param to the script and worked fine. If others also experiment the issue, we can update the script in the repo so the change is available out-of-the-clone :-)

**Comment by deors** [comment]
Closing the issue, then.
