### ISSUE TITLE
Local setup in VM with 2 GB RAM is not enough, 6 GB needed, 8 GB recommended

### ISSUE THREAD

**Issue by deors** [Accenture/adop-docker-compose#15]
As per my own tests with boot2docker, a local VM with 2 GB of RAM is not enough, leading to low performance and some weird behaviours along the way. I suggest to update the local-setup.sh script to increase resources for the local VM to 8 GB RAM and 2 vCPU. If ok, I can submit PR for the change.

**Comment by nickdgriffin** [comment]
I think this should be fixed in #83 so that at least the CI part of the pipeline succeeds.
