### ISSUE TITLE
Got 404 while creating index in elasticsearch

### ISSUE THREAD

**Issue by chuymarin** [Accenture/adop-docker-compose#150]
I'm trying to create a new index in elasticsearch from jenkins, here is the code that I'm executing:

```
curl -XPUT -u <user>:<password> -H kbn-version: 4.3.1 -i http://<ip>/elasticsearch/edms?pretty

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    38  100    38    0     0  17335      0 --:--:-- --:--:-- --:--:-- 19000
HTTP/1.1 404 Not Found
Server: nginx
Date: Mon, 03 Oct 2016 22:45:08 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 38
Connection: keep-alive
Vary: Accept-Encoding
kbn-name: kibana
kbn-version: 4.3.1
cache-control: no-cache

{"statusCode":404,"error":"Not Found"}
```

I'm following instructions from here: [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/_create_an_index.html#_create_an_index)

**Comment by anton-kasperovich** [comment]
Hello @chuymarin , as ElasticSearch is part of ELK stack, from Jenkins, i would suggest you to work with ElasticSearch directly, without proxying requests through NGINX.

```
[jenkins-slave /]# curl -XPUT 'elasticsearch:9200/edms?pretty'
{
  "acknowledged" : true
}
```

This way you wouldn't need even specify credentials as it's internal docker network between containers.

**Comment by chuymarin** [comment]
That's really helpful! thanks @anton-kasperovich, closing issue.
