### ISSUE TITLE
Host Timeout on OSX

### ISSUE THREAD

**Issue by acn-adammclark** [Accenture/adop-docker-compose#158]
```
local platform: OSX 10.10.5
Docker version 1.12.2, build bb80604
docker-machine version 0.8.2, build e18a919
```

I'm trying to get ADOP running in my personal AWS instance using the quickstart guide but I keep getting the error bellow.

I've run it about 6 different times. A few times from master, a few times from the tagged branch 0.2.2. I've tried it in different regions. 

Any help would be appreciated. 

```
      ###    ########   #######  ########
     ## ##   ##     ## ##     ## ##     ##
    ##   ##  ##     ## ##     ## ##     ##
   ##     ## ##     ## ##     ## ########
   ######### ##     ## ##     ## ##
   ##     ## ##     ## ##     ## ##
   ##     ## ########   #######  ##

Your AWS parameters file already exists, deleting it...
Creating a new AWS variables file...
Running pre-create checks...
Creating machine...
(sa-adop) Launching instance...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "52.211.83.224:2376": dial tcp 52.211.83.224:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

**Comment by anton-kasperovich** [comment]
Hi @acn-adammclark , is there's any chance that you have blocked 2376 port in your network? I've seen this error often and all those times it was related to blocked port unfortunately.

**Comment by acn-adammclark** [comment]
@anton-kasperovich that was the issue. Thanks for the help. Now to figure out why nginx never comes online.

**Comment by acn-adammclark** [comment]
Well I've waited for nearly 35 minutes for nginx to respond. Is this expected?

**Comment by anton-kasperovich** [comment]
No, it is not expected, usually it's take about ~2 minutes in total of sleep statements to have running NGINX. I've heard about some random errors which people can't reproduce, they've just re-created ADOP stack and everything worked perfectly fine. Is it your case too? Can you please re-create and check?

**Comment by acn-adammclark** [comment]
I figured it out. You have to change the security policy before quickstart gets around to testing for services. Port 80 isnt accepting incoming connecitons with the default policy docker sets up. 

I'll provide a PR to update the quickstart guide.

**Comment by arunamat** [comment]
@acn-adammclark Can you please share the steps that you followed to fix this issue? We are facing the same issue.

**Comment by adamclerk** [comment]
@arunamat The default security group that docker-machine creates doesn't have open ports that support ADOP. 

Take step 7 of the instructions
```
Update the docker-machine security group in the AWS console to permit inbound http traffic on port 80 (from the machine(s) from which you want to have access only), also UDP on 25826 and 12201 from 127.0.0.1/32.
```
and go into AWS console and update the ports after step 4 before step 5 while the images are being downloaded.
