### ISSUE TITLE
Vanilla ADOP installation doesn't seem to work

### ISSUE THREAD

**Issue by hjnijlunsing** [Accenture/adop-docker-compose#169]
I used a "blank" Cent-OS7 installation, installed the pre-requisites (Docker, Git, etc) and ran:

export COMPOSE_HTTP_TIMEOUT=900
adop compose init -verbose

After x minutes it resulted in a continuous: "Jenkins was unavailable, so slept for: 30 secs" 

Full replay: https://asciinema.org/a/6miv9bqfxyhx7defivf86fcbm

**Comment by nickdgriffin** [comment]
What size machine is being used please? Does it have 12-16GB of RAM?

**Comment by hjnijlunsing** [comment]
CentOS 7 with 6GB RAM:

[root@elite ~]# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
stepping        : 11
microcode       : 0xba
cpu MHz         : 1596.000
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                         pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant                                                                                        _tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vm                                                                                        x est tm2 ssse3 cx16 xtpr pdcm lahf_lm dtherm tpr_shadow vnmi flexpriority
bogomips        : 4787.97
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
stepping        : 11
microcode       : 0xba
cpu MHz         : 2400.000
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 2
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                         pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant                                                                                        _tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vm                                                                                        x est tm2 ssse3 cx16 xtpr pdcm lahf_lm dtherm tpr_shadow vnmi flexpriority
bogomips        : 4787.97
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
stepping        : 11
microcode       : 0xba
cpu MHz         : 1596.000
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                         pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant                                                                                        _tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vm                                                                                        x est tm2 ssse3 cx16 xtpr pdcm lahf_lm dtherm tpr_shadow vnmi flexpriority
bogomips        : 4787.97
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
stepping        : 11
microcode       : 0xba
cpu MHz         : 1596.000
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                         pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant                                                                                        _tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vm                                                                                        x est tm2 ssse3 cx16 xtpr pdcm lahf_lm dtherm tpr_shadow vnmi flexpriority
bogomips        : 4787.97
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

[root@elite ~]# cat /proc/meminfo
MemTotal:        5815452 kB
MemFree:         4747920 kB
MemAvailable:    5322160 kB
Buffers:            1812 kB
Cached:           722056 kB
SwapCached:            0 kB
Active:           566876 kB
Inactive:         331604 kB
Active(anon):     174996 kB
Inactive(anon):     8724 kB
Active(file):     391880 kB
Inactive(file):   322880 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       6029308 kB
SwapFree:        6029308 kB
Dirty:             78096 kB
Writeback:             0 kB
AnonPages:        174756 kB
Mapped:            32168 kB
Shmem:              9036 kB
Slab:              89896 kB
SReclaimable:      56828 kB
SUnreclaim:        33068 kB
KernelStack:        2448 kB
PageTables:         5272 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8937032 kB
Committed_AS:     378320 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      356244 kB
VmallocChunk:   34359377920 kB
HardwareCorrupted:     0 kB
AnonHugePages:      8192 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       67204 kB
DirectMap2M:     6092800 kB

**Comment by hjnijlunsing** [comment]
Memory does not seem to be the problem. looking at the quickstart.sh it would create a virtualbox machine with only 6Gb of memory. Thus w/o virtualbox it should also work with 6gb, correct?

**Comment by hjnijlunsing** [comment]
Ok, changed from Vanilla CentOS 7 to Vanilla Ubuntu 16.04.1
Now it just works...
