### ISSUE TITLE
ADOP setup in Client Environment.

### ISSUE THREAD

**Issue by AnkshSharma** [Accenture/adop-docker-compose#170]
Hi,

I was trying to setup ADOP platform in client environment. ADOP is not starting because of jenkin is unavailable.

Regards,
-Ankush

**Comment by NinjaPT** [comment]
@AnkshSharma can you paste the output from the initiation of ADOP, if there are any network restrictions or if the IP changed on the host?

**Comment by AnkshSharma** [comment]
Not able to access files, because of restricted network. Closing this issue. 

Thanks ,
-Ankush
