### ISSUE TITLE
Update the Provisioning Documentation

### ISSUE THREAD

**Issue by luismsousa** [Accenture/adop-docker-compose#174]
Opening this ticket to track the improvement of the site section on provisioning.

Plan:

- [x] Copy the quickstart guide on the main readme to the provisioning section
- [x] Add page for using the adop cli to stand up on an existing instance
- [ ] updat the troubleshooting steps page

**Comment by NinjaPT** [comment]
#175 Pull request for the first 2 topics fix.

**Comment by dsingh07** [comment]
Thanks @luismsousa, all relevant PRs are merged now. Can this issue be closed?

**Comment by dsingh07** [comment]
Closing this issue as all relevant PRs have been merged.
