### ISSUE TITLE
'Ngnix was unavailable' message loop during quickstart installation

### ISSUE THREAD

**Issue by parvez99** [Accenture/adop-docker-compose#183]
I am new to ADOP trying to get started with quickstart script. After setting up AWS credentials and prerequisites for ADOP evaluation mode, I tried executing quickstart.sh using default region eu-west-1 ( Ireland) where the script executes well up until Ngnix installation ! 

The script fails at "Waiting for Ngnix to become available " message followed by "Ngnix was unavailable" message loop. Is there any work around for this ? Am I missing something here. I looked up for some solution but couldn't find any.

**Comment by RobertNorthard** [comment]
@parvez99 does the docker-machine security group, which is assigned to your ADOP EC2 instance have TCP port 80 open? If not you'll need to add the rule.

**Comment by parvez99** [comment]
Hi RobertNorthard,

Thanks for the reply. Yes it was the port 80 issue. I now have the ADOP platform up and running .
Thanks again
