### ISSUE TITLE
Test connection at "Docker Builder" on Jenkins fails

### ISSUE THREAD

**Issue by pattyhama** [Accenture/adop-docker-compose#184]
Using ADOP with default configuration on my local machine, under Jenkins global configuration, I have specified Docker REST API URL (somethig like http://x.x.x.x (docker host ip, i.e. ADOP machine):2376)  to use docker command, however it gives result 

> Something went wrong, cannot connect to http://x.x.x.x:2376, cause: null

Could anyone advise this please?

Below is the Docker version (version should be new):

> Client:
>  Version:      1.12.5
>  API version:  1.24
>  Go version:   go1.6.4
>  Git commit:   7392c3b
>  Built:        Fri Dec 16 06:14:34 2016
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.12.5
>  API version:  1.24
>  Go version:   go1.6.4
>  Git commit:   7392c3b
>  Built:        Fri Dec 16 06:14:34 2016
>  OS/Arch:      linux/amd64

Below is the "Docker build step plugin" version of Jenkins:

> Release 1.35 (2016-05-11) 
> https://wiki.jenkins-ci.org/display/JENKINS/Docker+build+step+plugin

**Comment by nickdgriffin** [comment]
Is the x.x.x.x your local machine? Can you talk to that Engine normally using the Docker CLI?

**Comment by pattyhama** [comment]
> Is the x.x.x.x your local machine? Can you talk to that Engine normally using the Docker CLI?

Yes.

Jenkins(container) is running on my local machine (Docker Engine)
The "local machine" is running Docker with "-H tcp://0.0.0.0:2376" to accept.
Is it possible to reproduce on your end?

Now, the error result is more likely to be:
> Something went wrong, cannot connect to http://x.x.x.x:2376, cause: org.apache.http.client.ClientProtocolException

**Comment by nickdgriffin** [comment]
Had a look at that plugin and it doesn't seem to have favourable reviews, can you try running Docker commands within a shell block inside Jenkins and see if that works on its own?

If they do, I'd suspect the plugin being at fault and would suggest you try this one out instead (it's also included in ADOP):
https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Build+and+Publish+plugin

**Comment by pattyhama** [comment]
I tried curl to 2376 port and it works. Must be plugin's issue.
I will try the plugin that was suggested.
Thank you for your advise.

Closing issue.

2017年1月18日(水) 17:50 Nick Griffin <notifications@github.com>:
