### ISSUE TITLE
Jenkins Nexus integration

### ISSUE THREAD

**Issue by sergiolacolla** [Accenture/adop-docker-compose#196]
After all pipilines become finished I don't find any package into nexus repositories.

So I tried to deploy petclinic.war by curl command using Execute shell step in build task after install maven goal;  but nexus respond with   "500 Server Error".

Instead using deploy:deploy-file (I am sure that administrator password is ok in settings.xml) Nexus response is Unauthorized:
[WARNING] Could not transfer metadata org.springframework.samples:spring-petclinic:4.2.6-SNAPSHOT/maven-metadata.xml from/to snapshots (http://nexus:8081/nexus/content/repositories/snapshots): Not authorized , ReasonPhrase:Unauthorized.

Property in jenkins mvn pipeline:
groupId=org.springframework.samples
artifactId=spring-petclinic
version=4.2.6-SNAPSHOT
generatePom=false
packaging=war
repositoryId=snapshots
url=http://nexus:8081/nexus/content/repositories/snapshots/
file=target/petclinic.war

Logs Curl:

+ cd target
+ curl -v -F r=snapshots -F hasPom=false -F e=war -F g=com.spring.test -F a=petclinic -F v=1.0 -F p=war -F file=@petclinic.war -u administrator:qwerty11 http://nexus:8081/nexus/content/repositories/snapshots
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to nexus port 8081 (#0)
*   Trying 172.18.0.5...
* Connected to nexus (172.18.0.5) port 8081 (#0)
* Server auth using Basic with user 'administrator'
> POST /nexus/content/repositories/snapshots HTTP/1.1
> Authorization: Basic <removed>
> User-Agent: curl/7.29.0
> Host: nexus:8081
> Accept: */*
> Content-Length: 39280496
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=----------------------------e707398e1d13
> 
< HTTP/1.1 100 Continue
} [data not shown]
  2 37.4M    0     0    2 1088k      0  1811k  0:00:21 --:--:--  0:00:21 1811k
  7 37.4M    0     0    7 2704k      0  1711k  0:00:22  0:00:01  0:00:21 1711k
 11 37.4M    0     0   11 4288k      0  1634k  0:00:23  0:00:02  0:00:21 1633k
 16 37.4M    0     0   16 6416k      0  1792k  0:00:21  0:00:03  0:00:18 1792k
 24 37.4M    0     0   24 9264k      0  2022k  0:00:18  0:00:04  0:00:14 2022k
 49 37.4M    0     0   49 18.5M      0  3410k  0:00:11  0:00:05  0:00:06 3603k
 77 37.4M    0     0   77 29.1M      0  4532k  0:00:08  0:00:06  0:00:02 5422k< HTTP/1.1 500 Server Error
< Date: Mon, 27 Feb 2017 19:30:27 GMT
< Server: Nexus/2.11.3-01
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< Accept-Ranges: bytes
< Content-Length: 0
* HTTP error before end of send, stop sending
< 

100 37.4M    0     0  100 37.4M      0  5228k  0:00:07  0:00:07 --:--:-- 7230k
* Closing connection 0

**Comment by RobertNorthard** [comment]
Thanks @sergiolacolla. Are you still having this issue?

**FYI I have redacted your ADOP/C password from the log files in this issue. Please change your ADOP/C admin password if this stack is still in use**

**Comment by sergiolacolla** [comment]
I stopped checking with curl command because I worked on other servers where I had no problems using mvn deploy

**Comment by sergiolacolla** [comment]
No more issue,
I stopped checking with curl command because I worked on other servers where I had no problems using mvn deploy.

Thanks,

Sergio.
