### ISSUE TITLE
Local DNS not workin for my ADOP instalation

### ISSUE THREAD

**Issue by greg80** [Accenture/adop-docker-compose#211]
Hello!

For my installation containers can not communicate with other containers from adop using network aliases.

I installed ADOP on vm (ubuntu guest running as vm machine in VirtualBox). 

`adop compose init` command stopped at 

> "* Waiting for the Platform to become available - this can take a few minutes"

I'v checked manually and jenkins returned incorrect user or password error. 

I tried also login to ldap-phpadmin and got:

>  Can't contact LDAP server (-1) for user

message.

Then I started  ldap container manually, and for ldap-phpadmin container provided ldap server IP in yml configuration:

OLD:
`LDAP_SERVER_HOST: "ldap"`
NEW:
`LDAP_SERVER_HOST: "172.19.0.2"`

With that configuration I can login into to LDAP.

How to configure this installation to make containers communicate using network aliases?

**Comment by nickdgriffin** [comment]
Hello!

That's a feature of Docker container networks, and the hostname that is selected is the "container_name" from the docker-compose.yml.

This feels like more of a Docker problem than an ADOP one, are there any errors in your Engine log that might suggest there's a problem with networking?

Nick

**Comment by greg80** [comment]
Hi!

What is interesting in /etc/hostname of the example adop-ldap container hostname is set to 9272fa40fcfd (it is container ID). The same value is returned in `docker inspect ldap` results:

>  "Config": {
>             **"Hostname": "9272fa40fcfd",**
>             "Domainname": "",
>             "User": "",
>             "AttachStdin": false,
>             "AttachStdout": false,
>             "AttachStderr": false,
>             "ExposedPorts": {
>                 "389/tcp": {}
>             },


>  "Networks": {
>                 "adop_network": {
>                     "IPAMConfig": null,
>                     "Links": null,
>                     "Aliases": [
>                         **"9272fa40fcfd"**
>                     ],
>                     "NetworkID": "2a45eb4d775380275b86df0eb32961de0e5cd2518c76d27ecf741e9eca8b7d72",
>                     "EndpointID": "a7235f99090585b980a11b5757fe0fa4eb4f8ce4f5902a8a769f39949b0fbcbf",
>                     "Gateway": "172.19.0.1",
>                     "IPAddress": "172.19.0.4",
>                     "IPPrefixLen": 16,
>                     "IPv6Gateway": "",
>                     "GlobalIPv6Address": "",
>                     "GlobalIPv6PrefixLen": 0,
>                     "MacAddress": "02:42:ac:13:00:04"
>                 }


I'm running docker version: 1.12.6. I got the  same result on boot2docker image v17.04.0-ce

Could you please confirm on which version of docker aliases are set correctly? I will also try to run it on default network and check how it works.

Greg

**Comment by nickdgriffin** [comment]
Hi Greg,

I've not had/see an issue like this in Docker 1.10.x or later, including 1.12.6.

Was there anything in the Engine log to suggest a problem?

Regards,
Nick

**Comment by greg80** [comment]
Hi,

I stopped investigating the issue. As a workaround in docker-compose.yml I defined _hostname_ property for each container. For example:
`hostname: proxy`

Regards,
Greg

**Comment by nickdgriffin** [comment]
Hi Greg,

That's interesting, as the container_name value should be the one taken as the hostname. What version of Compose are you using?

Regards,
Nick

**Comment by RobertNorthard** [comment]
Closing issue @greg80 as it's been a while since reporting. Please let is know if you are still having trouble.
