### ISSUE TITLE
Hardcoded usernames in cmd/compose

### ISSUE THREAD

**Issue by avoidik** [Accenture/adop-docker-compose#212]
Hi,

Please pay attention on hardcoded usernames when linking this repository from your own scripts:

https://github.com/Accenture/adop-docker-compose/blob/master/cmd/compose#L156
https://github.com/Accenture/adop-docker-compose/blob/master/cmd/compose#L157
https://github.com/Accenture/adop-docker-compose/blob/master/cmd/compose#L164

**Comment by nickdgriffin** [comment]
Hello,

I'm not clear what the issue is here, or are you suggesting it'd be convenient for these values to be environment variables so that other scripts can make use of them once sourced?

Thanks,
Nick

**Comment by avoidik** [comment]
Yes, it would be great if those username will be defined as variables. Right now I've to use sed to replace those values.

**Comment by avoidik** [comment]
Incorrect credential values introduces infinity awaiting loops for services to came up.
