### ISSUE TITLE
Ngnix Stuck on quickstart link

### ISSUE THREAD

**Issue by santhh** [Accenture/adop-docker-compose#216]
Hello: I am trying with AWS. 
Script is stuck in this. Any idea on why it's in this loop?

* Waiting for Nginx to become available
Nginx was unavailable, so slept for: 5 secs
Nginx was unavailable, so slept for: 5 secs
Nginx was unavailable, so slept for: 5 secs

**Comment by santhh** [comment]
I have also noticed this. If AWS deploy fails for cert issue, will it be installed locally? when I did docker ps i saw all the processes running. May be the first looping issue relate to memory in local?

* Bringing up ADOP...
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "54.70.15.223:2376": x509: certificate is valid for 34.210.57.148, not 54.70.15.223
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.

**Comment by santhh** [comment]
Provisioning to AWS is having some issues.  Has anyone seen this before?
if [ ${MACHINE_TYPE} == "aws" ]; then
    ./adop certbot gen-export-certs "registry.$(docker-machine ip ${MACHINE_NAME}).nip.io" registry
fi* Bringing up ADOP...
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "35.167.200.54:2376": dial tcp 35.167.200.54:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.

**Comment by nickdgriffin** [comment]
Hello,

The first issue implies that either Nginx is not able to start, or that you do not have connectivity to Nginx.

The second issue suggests that the IP of the machine has been changed as Docker Machine has generated them for one IP but the machine has another IP - you can fix that with the suggested command though.

The third issue suggests you do not have connectivity to port 2376.

Thanks,
Nick

**Comment by RobertNorthard** [comment]
Closing this issue as no response.
