### ISSUE TITLE
Feature request-- Serverless test automation framework

### ISSUE THREAD

**Issue by subratafouzder** [Accenture/adop-docker-compose#224]
HI 
Can we have  AWS lambda function to be invoked ( GItlab. hooks or event) , which can call a test automation  framework  to be run on Chrome headless mode.
The framework will produce all the report and we can have a parallel configurable multi threading which Lambda can scale infinitely to give us on demand infinitely sclable  test automation environment.

**Comment by nickdgriffin** [comment]
Hello,

Can you give some more details/an example of how this could work please?

Thanks,
Nick

**Comment by RobertNorthard** [comment]
I'm closing this issue as there has been no response for a year.
