### ISSUE TITLE
Docker Compose File has Incorrect Port Format

### ISSUE THREAD

**Issue by garystafford** [Accenture/adop-docker-compose#228]
The `docker-compose.yml` has two errors in the way ports are exposed, causing an error while spinning up ADOP using the latest version of Docker. For example, `ERROR: Invalid published port: 50000/tcp`.

Line 32: `- "389/tcp:389/tcp"` should be `- "389:389/tcp"`
Line 209: `- "50000/tcp:50000/tcp"` should be `- "50000:50000/tcp"`

**Comment by svscorp** [comment]
Was implemented and tested in #241 @nickdgriffin

**Comment by RobertNorthard** [comment]
Closing as merged in https://github.com/Accenture/adop-docker-compose/pull/241
