### ISSUE TITLE
Getting error while setting up ADOP 

### ISSUE THREAD

**Issue by soham-k** [Accenture/adop-docker-compose#237]
Getting following error on running command ./adop compose init

Digest: sha256:82523c240fe1c276094f3cec284e8510e6c053266aabceb84a76cf03b6297e0f
Status: Downloaded newer image for accenture/adop-ldap-ltb:0.1.0
Pulling nexus (accenture/adop-nexus:0.1.3)...
ERROR: Get https://registry-1.docker.io/v2/accenture/adop-nexus/manifests/0.1.3: x509: certificate signed by unknown authority

**Comment by nickdgriffin** [comment]
Hi,

That sounds like a problem with docker.io and as far as I'm aware isn't related to our images. In the past when I've seen certificate/registry issues they've gone away when retrying.

Kind Regards,
Nick

**Comment by soham-k** [comment]
Thanks !
