### ISSUE TITLE
Getting error after running ./quickstart

### ISSUE THREAD

**Issue by soham-k** [Accenture/adop-docker-compose#238]
Hi ,
I run the following command to install ADOP locally.
./quickstart.sh -t local -m adopdemotest  -c NA  -u user.name -p userPassword
Getting  following error

* Waiting for the Platform to become available - this can take a few minutes
* Loading the Platform
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /jenkins/job/Load_Platform/buildWithParameters. Reason:
<pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
Generating client certificates for TLS-enabled Engine

**Comment by RobertNorthard** [comment]
@soham-k we are unable to repeat this issue and as it has been almost a year since reported I am closing. Please let us know if you are still experiencing it.
