### ISSUE TITLE
Need Help: how to add plugin on sonar qube server

### ISSUE THREAD

**Issue by soham-k** [Accenture/adop-docker-compose#239]
I want to add some reporting framework for sonar qube. How to add plugin on ADOP .

**Comment by nickdgriffin** [comment]
Hello!

If you mean in a permanent capacity, you'd need to submit a PR to the [adop-sonar](https://github.com/Accenture/adop-sonar) repository to change this file: https://github.com/Accenture/adop-sonar/blob/master/resources/plugins.txt . It would need to contain a URL to the plugin JAR, from a trusted source.

If you wanted a bespoke image you could follow the same process and just replace your container with the new custom one, or just install the plugin the normal way.

Kind Regards,
Nick

**Comment by RobertNorthard** [comment]
Closing issue as resolution provided.
