### ISSUE TITLE
quickstart link stuck in nginx

### ISSUE THREAD

**Issue by jaynathani-granube** [Accenture/adop-docker-compose#246]
Hello. I created the VPC on AWS and started the quickstart.sh script. It works perfectly until it searches for nginx.

It is stuck in a loop as seen following:
Waiting for Nginx to become available
Nginx was unavailable, so slept for: 5 secs
Nginx was unavailable, so slept for: 5 secs
Nginx was unavailable, so slept for: 5 secs

I waited for 20 minutes and it didn't move forward from there.

Can you help me with this?

Also, I see that a m4xlarge EC2 instance is created with the quickstart kit. Is there a way to change the EC2 instance type. Further, where can I find the created KeyPair so that I am able to ssh into the EC2 instance?

Thanks for your help.

**Comment by nickdgriffin** [comment]
Hello,

Have you checked the security group that it has created? By default it only opens ports 22 and 2376, so 80 will be blocked and is probably the cause of that "issue" - the tools will be up, it just can't connect (as that's what that section does, it's the first time it tries to access the IP).

If you'd like to change the instance type you can either tweak it inside the quickstart script, or run Docker Machine independently then use the ADOP CLI directly (that's all quickstart does). The keypair is created by Docker Machine so the easiest way to SSH is by doing "docker-machine ssh <name of your machine>" as the key is tucked away in your .docker directory.

Kind Regards,
Nick

**Comment by jaynathani-granube** [comment]
Hi Nick,

Thanks for your response. I have been able to setup ADOP on a VPC on AWS. Thank you for the tip on using _docker-machine ssh_ for SSH. I am planning to set up a pipeline using the tools that are mentioned in ADOP. Are there any sample cartridges available for me to use?

Also, I saw there is also a way to setup all the resources on AWS using a CloudFormation template. Are there any ADOP configured CloudFormation templates that I can use?

Thanks
Jay

**Comment by nickdgriffin** [comment]
Hi Jay,

So out of the box the Load_Cartridge job lists all of the cartridges that are available on GitHub - the Java cartridge should be loaded by default for you under ExampleWorkspace/ExampleProject too. There is also a skeleton cartridge referenced from the development materials here: https://accenture.github.io/adop-docker-compose/docs/developing/cartridges/

For launching via AWS we have a repository with a reference architecture in it (containing a two-tier network and VPN): https://github.com/Accenture/adop-aws

Cheers,
Nick

**Comment by jaynathani-granube** [comment]
Hi Nick,

Thank you for the information. I was able to set up a pipeline using the java-cartridge. The pipeline works great for all stages except it got stuck in ProdA stage. The console gives the following error: 

+ docker cp /workspace/workspace-1/project-1/root/Reference_Application_Deploy_ProdA/target/petclinic.war workspace-1_project-1_root_PRODA:/usr/local/tomcat/webapps/
no such directory
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Finished: FAILURE

I installed tomcat8 by doing ssh into docker machine. I moved the installed tomcat folder to the mentioned directory, /usr/local/. I also renamed the folder to _tomcat_ and double checked whether the contents of the folder include the _/webapps/_ folder. Even after doing this, the build fails and gives me the same error. Can you please give some advice on how I can fix this?

Thanks 

Jay

**Comment by nickdgriffin** [comment]
Hi Jay,

Have you created the Prod environment using the environment creation pipeline? The cartridge assumes that is in place and tries to make use of it, I think the problem there is that it can't find the "Prod A" Tomcat container which is where it is trying to copy to.

Cheers,
Nick

**Comment by jaynathani-granube** [comment]
Hi Nick,

I went to Java Application Reference tab in the cartridge folder I created and ran the pipeline that had come up on its own. Are there any other steps I should take to create ProdA environment?

Thanks,
Jay

**Comment by nickdgriffin** [comment]
Hi Jay,

That's the build pipeline, there should also be an environment creation pipeline where the first job will allow you to pick the type of environment.

Cheers,
Nick

**Comment by jaynathani-granube** [comment]
[prodA console output.txt](https://github.com/Accenture/adop-docker-compose/files/1322090/prodA.console.output.txt)
Hi Nick,

Thank you so much. That worked like a charm. But I am not able to see the application (petclinic). I went into the console for ProdA and found **http://workspace-1_project-1_root_PRODA.PUBLIC_IP.xip.io/petclinic** url. I changed the PUBLIC_IP to the public IP I have of the EC2 instance, it gives me a 404 not found error. Also, I have attached the console output of ProdA. Kindly take a look.

Thanks
Jay

**Comment by surajshettyakkunje** [comment]
HI @nickdgriffin .
Can you please elaborate on the Nginx was unavailable, so slept for:5 secs
It will be of great help.. what do i need to change here.. so that this issue gets resolved.

**Comment by nickdgriffin** [comment]
@surajshettyakkunje : Is this related to the above issue? If not I think a new one should be raised.

In any case, that loop is the first time that connectivity is tested from outside of the Engine so if it is looping forever it means that either there is a connectivity issue between you and Nginx or that Nginx has failed to start. If it is the latter you can check that by doing "docker ps" against the Engine to see if it's restarting, and if you've added other configuration it is likely because it is invalid or that it cannot resolve the DNS/hostnames that are being used.

**Comment by surajshettyakkunje** [comment]
Hi Nick,

Just as a matter of curiosity.
I had my Nginx unavailable and it said --> so slept for : 5sec.
I am running the quickstart cmd on my local using a AWS VPN.
I have a jenkins instance on my local hosted on port 80.. And in the docker-compose.yml it shows
restart: always
  image: accenture/adop-nginx:0.3.2
  #build: ../images/docker-nginx/
  net: ${CUSTOM_NETWORK_NAME}
  ports:
    - "80:80"
    - "443:443"

so is Nginx trying to open on port 80 which is already being used by Jenkins in my local...

**Comment by nickdgriffin** [comment]
If port 80 is already taken on the host that you are launching on then yes that will cause a problem.
