### ISSUE TITLE
issue with Jenkins permission

### ISSUE THREAD

**Issue by kihyunsung** [Accenture/adop-docker-compose#260]
Hi there

I have installed the ADOP platform today, and when I browse to Jenkins I get a message like below.

**Access Denied
iomadmin is missing the Overall/Read permission**

On another ADOP platform which was installed in November 2017 (exactly the same way), there was no issue with Jenkins.

iomadmin is the admin user that was input when creating the ADOP platfrom from the script.

Everything else like the Dashboard, Selenium, Sonarqube etc can be browsed without issues.
What could be the reason for Jenkins issue here?

Regards

**Comment by RobertNorthard** [comment]
@kihyunsung I think this is a race condition in load platform (I've had trouble debugging in the past). Please can you re-create the platform and let me know if the issue persists?

**Comment by kihyunsung** [comment]
@RobertNorthard 
For some weird reason Jenkins permission issue is gone once I run the below command in the server where the ADOP platform has been deployed.
**docker-compose restart**

However Jenkins is excruciatingly slow (around 20 seconds to load when I click anything in Jenkins).
Other apps are running fine.

Do you still want me to stand up another ADOP instance on another server?

Cheers

**Comment by RobertNorthard** [comment]
Okay thanks @kihyunsung. I am closing this issue as we are unable to repeat problems with permissions.

For Jenkins being slow please check if you have any firewalls / adblockers?
