### ISSUE TITLE
after install with docker enkins not running

### ISSUE THREAD

**Issue by aermike** [Accenture/adop-docker-compose#296]
Hi 
i follow the steps described in 
https://accenture.github.io/adop-docker-compose/docs/provisioning/adop_cli/
after pulling and creating all machines  jenkins doesn't start
Jenkins unavailable, sleeping for: 9s

**Comment by aliciasteen** [comment]
Hi @aermike Could you post the command you used and the logs from the containers to see what the error is. You might need to add the  `--with-stdou` flag to your `./adop init` command.

**Comment by aermike** [comment]
Hi
Thank you for answer
it work with ./adop init
where i can put IP for machine?

--------------------------------------------
On Thu, 11/8/18, Alicia Steen <notifications@github.com> wrote:

 Subject: Re: [Accenture/adop-docker-compose] after install with docker enkins not running (#296)
 To: "Accenture/adop-docker-compose" <adop-docker-compose@noreply.github.com>
 Cc: "aermike" <mike_dana_iasi@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Thursday, November 8, 2018, 6:45 PM
 
 Hi @aermike Could you
 post the command you used and the logs from the containers
 to see what the error is. You might need to add the 
 --with-stdou flag to your ./adop
 init command.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by aliciasteen** [comment]
Hi @aermike 
You can specify the IP using the `-i <ip>` flag: https://accenture.github.io/adop-docker-compose/docs/provisioning/adop_cli/ where you replace `<proxy_ip>` with your IP address.

**Comment by aermike** [comment]
thank you

**Comment by RobertNorthard** [comment]
Thanks @aliciasteen. Closing issue as no further actions.

@aermike please raise another issue if you are experiencing any further issues.
