### ISSUE TITLE
When using the startup.sh script my inline options get overridden by what is in the .aws folder 

### ISSUE THREAD

**Issue by gogodi91** [Accenture/adop-docker-compose#30]
When I try running the startup.sh with my aws access key in order to spin up an instance in aws and use that for my ADOP, whatever I put inline gets overridden by my .aws folder content. This behavior is bad as it means I cannot use the command line for one time operations and I need to fill in new parameters in my .aws options every time I want to use new access credentials. Also I was met by the error ./startup.sh: line 115: output: command not found.

A workaround is to temporarily move the .aws folder and run the startup.sh

**Comment by gogodi91** [comment]
The same behavior is observed when running quickstart.sh. This time the error is ./quickstart.sh: line 58: output: command not found.

**Comment by SachinKSingh28** [comment]
@gogodi91 - I believe #103 fixes this issue. Are you happy for me to close this?

**Comment by RobertNorthard** [comment]
Closing as resolved by @SachinKSingh28
