### ISSUE TITLE
Install and run ADOP locally

### ISSUE THREAD

**Issue by onegarzon** [Accenture/adop-docker-compose#308]
Good afternoon Team,
I would like to setup ADOP on my local env running iOS.

Can you share in more details a set of instructions with specific steps in order to spin up ADOP?

Current Specs:
**Docker Desktop Community**
- Version 2.0.0.3 (31259)
- Engine: 18.09.2
- Compose: 1.23.2
- Machine: 0.16.1
- Kubernetes: v1.10.11

My sincere apologies. Thanks for your guidance and support,
garzon

**Comment by RobertNorthard** [comment]
Hi @onegarzon,

You can either spin up ADOP/C on AWS using the following [instructions](https://accenture.github.io/adop-docker-compose/docs/quickstart/). 

Or if you have a local VM with Docker engine installed you can use the quickstart script from this repository in local mode to provision ADOP locally. You will need at least 6GB of memory allocated to the VM.

`./quickstart.sh 
	    -t local 
	    [-m <MACHINE_NAME>] 
	    [-u <INITIAL_ADMIN_USER>] 
	    [-p <INITIAL_ADMIN_PASSWORD>]`

Please let me know if you have any questions.

**Comment by RobertNorthard** [comment]
Closing issue as no response.
