### ISSUE TITLE
Creation of docker-machine via quickstart script getting failed

### ISSUE THREAD

**Issue by Rajeswari-31** [Accenture/adop-docker-compose#313]
I am setting up the ADOP C on my local windows. I have installed the pre-requisites as mentioned in the documentation. 
I have executed the below command.
**./quickstart.sh -t local -m adopc -u xxx -p xxx**
Currently I don't have any docker-machine. So the script will create a docker-machine named adopc. On creating am getting the below response. I see similar issues but not the solution. 

_Running pre-create checks...
Creating machine...
(adopc) Copying C:\Users\xxx\.docker\machine\cache\boot2docker.iso to C:\Users\xxx\.docker\machine\machines\adopc\boot2docker.iso...
(adopc) Creating VirtualBox VM...
(adopc) Creating SSH key...
(adopc) Starting the VM...
(adopc) Check network to re-create if needed...
(adopc) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.
(adopc) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Error creating machine: Error running provisioning: Could not find matching IP for MAC address xxx
Error checking TLS connection: Could not find matching IP for MAC address xxx_

          ###    ########   #######  ########
         ## ##   ##     ## ##     ## ##     ##
        ##   ##  ##     ## ##     ## ##     ##
       ##     ## ##     ## ##     ## ########
       ######### ##     ## ##     ## ##
       ##     ## ##     ## ##     ## ##
       ##     ## ########   #######  ##

_* Initialising ADOP
The specified Docker Machine does not exist: adopc
HINT: Either specify one with 'adop compose -m <name>', or use 'eval $(docker-machine env adopc)'_

_$ **docker-machine ls**
NAME    ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
adopc   *        virtualbox   Running                 Unknown   Could not find matching IP for MAC address xxx_

**Comment by RobertNorthard** [comment]
Thanks @Rajeswari-31 for raising this.

Were you able to resolve the issue with VirtualBox?

**Comment by RobertNorthard** [comment]
Closing as no response.
