### ISSUE TITLE
Kibana cannot be configured, it says 'Unable to fetch mapping'

### ISSUE THREAD

**Issue by deors** [Accenture/adop-docker-compose#48]
As per instructions, when a brand new ADOP instance is provisioned, I try to configure indices in Kibana dashboard. However, when I type logstash-* as index name, below appears a message saying 'Unable to fetch mapping. Do you have indices matching the pattern?'.
Any ideas about what could be causing this, or any known workaround?
Thanks in advance.

**Comment by nickdgriffin** [comment]
I believe this is the fault of a Docker Compose 1.6 bug where it does not merge the log driver config from the override file - so no data makes it into ELK. If the "docker logs" command still works, that's an indication.

**Comment by larrywright** [comment]
I ran into this the other day, and came to the same conclusion as Nick. ELK is working because I can manually send data to it, but the log drivers aren't sending data to them, and therefor the index never gets created.

**Comment by iniweb** [comment]
Docker compose v1.7.0 was recently released, this version should fix this problem

```
Fixed a bug where log_opt and log_driver were not properly carried over
when extending services in the v1 Compose file format.
```

https://github.com/docker/compose/releases/tag/1.7.0

**Comment by deors** [comment]
Docker Toolbox 1.11.0 is also released. Time to try it then!

**Comment by nickdgriffin** [comment]
Hopefully it's actually fixed and hasn't introduced another host of problems like Compose 1.6.0 did.

**Comment by larrywright** [comment]
I upgraded to the new version of the Docker Toolbox and can confirm that it's fixed.

**Comment by iniweb** [comment]
Tested on upgraded Docker compose v1.7 (Ubuntu 14.04) and everything works as well

**Comment by deors** [comment]
tested after upgrade to Toolbox 1.11 and on new instance and works fine. closing the issue now.

**Comment by acn-lianne-k-b-visperas** [comment]
'Unable to fetch mapping. Do you have indices matching the pattern?'.

Encountering same issue now. Already upgraded Docker Engines and Docker Compose versions to latest

Docker Engine Version= 
Docker Compose Version=
![image](https://user-images.githubusercontent.com/35712576/45017876-4e7b0e00-b05b-11e8-8e09-bcab914036ca.png)
