### ISSUE TITLE
has the behavior of quickstart.sh changed? it used to build, then launch a docker machine. now it doesn't seem to launch.

### ISSUE THREAD

**Issue by teamschwarz** [Accenture/adop-docker-compose#68]

**Comment by dsingh07** [comment]
Should be fixed by this pull request [here](https://github.com/Accenture/adop-docker-compose/pull/69)

**Comment by nickdgriffin** [comment]
@teamschwarz  Can you confirm if this issue can be closed now or not please?

**Comment by RobertNorthard** [comment]
Closing as no response.
