### ISSUE TITLE
ADOP VM memory specs 

### ISSUE THREAD

**Issue by emgsilva** [Accenture/adop-docker-compose#81]
I have been playing with ADOP, and getting it up (installed) and running takes a very good deal of time! I did not change the default memory allocated to creating the VM, and was wondering if something was not working fine. After a while, I simply increase the default memory from 2GB to 4GB and creation/startup times got "more reasonable". 

Do you have any experience on "minimal" memory that should be allocated to the VM in order to have the whole platform running smoothly?

Cheers!

**Comment by nickdgriffin** [comment]
We've got this issue already raised on this topic: #15

Basically, the more the merrier!

**Comment by emgsilva** [comment]
Thank you Nick! Did not see the other issue!

Nevertheless, I think it would be good to define a higher default (like proposed on the other issue - maybe 8GB is too much as default though - but should be mentioned as the optimal), and make it clear on the documentation / requirements, as it may lead to strange situations!

**Comment by nickdgriffin** [comment]
That's why I asked for a PR :)
