### ISSUE TITLE
Reference_Application_Performance_Tests job failing due to not finding apache-jmeter-2.13.tgz

### ISSUE THREAD

**Issue by midalias** [Accenture/adop-docker-compose#93]
The job Reference_Application_Performance_Tests job is failing due to not finding apache-jmeter-2.13.tgz file specified on section "Execute shell". The file is not listed on https://www.apache.org/dist/jmeter/binaries/. The file listed is apache-jmeter-3.0.tgz.

I modified the job (on a deployed Jenkins) to use the apache-jmeter-3.0.tgz and I am getting error "BUILD FAILED
/workspace/ExampleWorkspace/ExampleProject/Reference_Application_Performance_Tests/jmeter-test/apache-jmeter-3.0/extras/build.xml:132: stylesheet /workspace/ExampleWorkspace/ExampleProject/Reference_Application_Performance_Tests/jmeter-test/apache-jmeter-3.0/extras/**jmeter-results-detail-report_21.xsl doesn't exist.**"

I checked the /workspace/ExampleWorkspace/ExampleProject/Reference_Application_Performance_Tests/jmeter-test/apache-jmeter-3.0/extras/build.xml and on it comes "<xslt classpathref="xslt.classpath" force="true" in="${testpath}/${test}.jtl" out="${testpath}/${test}.html" style="${basedir}/jmeter-results-detail-report${**style_version**}.xsl">". It seems the style_version depends on the value on property format. As the value is 2.1, the style_version value is returned as "_21"

I added this to the "Execute shell" section:
#Idalia
if [ ! -f ${WORKSPACE}/$JMETER_TESTDIR/apache-jmeter-3.0/extras/jmeter-results-detail-report_21.xsl  ]; then
    echo "File jmeter-results-detail-report_21.xsl not found!"
    echo "Copying jmeter-results-detail-report.xsl as file jmeter-results-detail-report_21.xsl"
    cp ${WORKSPACE}/$JMETER_TESTDIR/apache-jmeter-3.0/extras/jmeter-results-detail-report.xsl ${WORKSPACE}/$JMETER_TESTDIR/apache-jmeter-3.0/extras/jmeter-results-detail-report_21.xsl 
fi

and the job was successful.

**Comment by deors** [comment]
I think we should revert to 2.13 until we've had the time to explore the upgrade path, not only for style version, also to verify that existing scripts work well once the version is bumped to 3.0

**Comment by midalias** [comment]
@nickdgriffin said this on Hipchat: "Griffin, Nicholas·Jun-2 9:30 AM
OK. Really we need to find a working URL for that binary and then update the cartridge with it I think, that'd be the quickest fix. I don't know enough about JMeter to know if jumping to 3.0 will cause issues - plus if that binary moves we'll just have the same issue next time."

Giovanni helped me to find the URL where the file apache-jmeter-3.0.tgz. is. I updated it on the jenkins job and sent an email to @nickdgriffin with it.

**Comment by midalias** [comment]
@deors, I tested the use of the version 3.0 and it worked, but after reading @nickdgriffin's comment I started looking for the URL of the 2.13 version. My coworker Giovanni found it and I updated in the jenkins job (deployed not script/image). I also sent to Nick the URL so his team can update it in the right item in the repository.

Thanks for reading the issue and providing your point of view.

**Comment by deors** [comment]
Regarding the location of the binary, it should not be needed if we leverage the Maven JMeter plug-in. That plug-in isolates the location of JMeter binaries and reduces the dependency with the actual location of the project binaries, as it only needs the binary artifact in Maven's central. The ref pipeline from blueprint leverages it and we have the approach documented in detail in the blueprint guidelines.
I will ask my team in global Java to take a look at that job configuration.
Regarding version jump, I would still be careful: there are tons of projects using JMeter and a change in major version could make scripts to break, or integration with SonarQube to break. We usually exercise caution before moving forward a tool version, just to ensure everything is still working fine.

**Comment by deors** [comment]
By the way, should this issue be moved to adop-java-cartridge repo instead of adop-docker-compose? Can it be done, @nickdgriffin?

**Comment by nickdgriffin** [comment]
Can this be closed here and raised in the correct repository please?
https://github.com/Accenture/adop-cartridge-java

**Comment by midalias** [comment]
Closing the issue as the solution (PR https://github.com/Accenture/adop-cartridge-java/pull/26) was merged into the repository.
