### ISSUE TITLE
Reference_Application_Regression_Tests job randomly failing because the 2 containers are not created on the same host

### ISSUE THREAD

**Issue by midalias** [Accenture/adop-docker-compose#95]
Two docker containers are created during the build of the Reference_Application_Regression_Tests job. When the containers are created on different hosts in a Docker swarm, the job fails with error "Cannot locate configuration source zap-test.session"

**Comment by midalias** [comment]
**Solution**: With support from @nickdgriffin, we modified the "Execute shell" section of the job adding " -e affinity:container==jenkins-slave" to the _docker run_ commands so that the containers will be created on the same host the jenkins-slave container is. 

I sent an email to Nick on 06/03/2016 with the the solution described above.

**Comment by nickdgriffin** [comment]
Can this be closed here and raised in the correct repository please?
https://github.com/Accenture/adop-cartridge-java

**Comment by midalias** [comment]
Closing the issue as the solution ([PR 26](https://github.com/Accenture/adop-cartridge-java/pull/26)) was merged.
