### ISSUE TITLE
/job/ExampleWorkspace/job/ExampleProject/job/Create_Environment job randomly failing on a Docker Swarm deployment

### ISSUE THREAD

**Issue by midalias** [Accenture/adop-docker-compose#96]
Some times the Create_Environment job fails with error “nginx: [error] open() ‘/run/nginx.pid’ failed (2: No such file or directory)” 

We believe this errors is because the nginx process is not started by the moment of the job's execution. If that's the case, Giovanni and I think we can solve this using either a loop or a sleep command. It needs to be tested.

**Comment by nickdgriffin** [comment]
Can this be closed here and raised in the correct repository please?
https://github.com/Accenture/adop-cartridge-java

**Comment by midalias** [comment]
Closing this issue. It will be raised again in the [adop-cartridge-java repository](https://github.com/Accenture/adop-cartridge-java) as requested by @nickdgriffin.

**Comment by midalias** [comment]
New issue is Issue 28 [here](https://github.com/Accenture/adop-cartridge-java/issues/28)
