### ISSUE TITLE
Latest Tag of sstarcher/uchiwa broke ADOP sensu-uchiwa service

### ISSUE THREAD

**Issue by bzon** [Accenture/adop-docker-compose#98]
I just noticed a while ago while testing adop that sensu uchiwa service is not working as it used to be last night and I saw that there is a new tag that was pushed to this repo. To fix, I had to hardcode the last working version to 0.15.0. 

sensu-uchiwa:
  container_name: sensu-uchiwa
  restart: always
  **image: sstarcher/uchiwa:0.15.0**
  net: ${CUSTOM_NETWORK_NAME}
  environment:
    SENSU_HOSTNAME: sensu-api
  expose:
    - "3000"

**Comment by anton-kasperovich** [comment]
@bzon image was tagged and merged, please check it

**Comment by bzon** [comment]
Thanks @anton-kasperovich. closing this issue now
